# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/retail_analysis',
                'doc_host': 'https://Vipulc659.github.io',
                'git_url': 'https://github.com/Vipulc659/retail_analysis',
                'lib_path': 'retail_analysis'},
  'syms': {'retail_analysis.core': {'retail_analysis.core.foo': ('core.html#foo', 'retail_analysis/core.py')}}}
